---
r1:
  hostname: 192.168.158.223
  platform: ios
  username: admin
  password: cisco
  groups:
    - ios

sw1:
  hostname: 192.168.158.220
  platform: ios
  username: admin
  password: cisco
  groups:
    - ios
