# Generated by Django 5.2.1 on 2025-05-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tasklog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime_seconds', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_records', to='network.networkdevice')),
            ],
        ),
    ]
