# Generated by Django 5.2.1 on 2025-05-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tasklog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='custom_command',
            field=models.TextField(blank=True, null=True),
        ),
    ]
